"Resources"
{
	"materials/hud/leaderboard_class_demo_clusterbomb.vmt"	"file"
	"materials/hud/leaderboard_class_demo_clusterbomb.vtf"	"file"
	"materials/hud/leaderboard_class_demo_loosecannon.vmt"	"file"
	"materials/hud/leaderboard_class_demo_loosecannon.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_natascha_ver2.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_natascha_ver2.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_rocket_hyper.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_rocket_hyper.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_phlog.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_phlog.vtf"	"file"
	"materials/hud/leaderboard_class_scout_cola.vmt"	"file"
	"materials/hud/leaderboard_class_scout_cola.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_airstrike.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_airstrike.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_bison.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_bison.vtf"	"file"
}